/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "ubt/bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_accelerometer                    8
#define gattdb_magnetometer                    12
#define gattdb_temperature                     16
#define gattdb_gyro                            20
#define gattdb_irradiance                      24
#define gattdb_wiper_freq                      28
#define gattdb_swept_freq_idx                  32
#define gattdb_pressure                        36
#define gattdb_xgatt_rev                       40
#define gattdb_AnlErrCnt                       45
#define gattdb_AnlErrCd                        49
#define gattdb_AnlDevCd                        53
#define gattdb_AnlTickCnt                      57
#define gattdb_AnlHrtBt                        61

#endif
